name: langhire
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip
  - pip:
    - streamlit>=1.28.0
    - langchain>=0.1.0,<0.3.0
    - langchain-google-genai>=1.0.0,<2.0.0
    - langchain-community>=0.0.10,<1.0.0
    - langchain-core>=0.1.0,<1.0.0
    - PyPDF2>=3.0.0
    - requests>=2.31.0
    - beautifulsoup4>=4.12.0
    - python-dotenv>=1.0.0
    - pandas>=2.0.0
    - plotly>=5.17.0